import { createAdminClient } from '@/core/supabase/admin';
import { guruProducerId, normalizeGuru } from '@/lib/webhooks/normalize';
import { executeWebhookDelivery } from '@/lib/webhooks/delivery';
import { hasPaymentDatabase, invalidWebhookBodyResponse, paymentPreflight, readWebhookJson, secretMatches, unavailablePaymentResponse } from '@/lib/webhooks/http';

export async function POST(request: Request, { params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  // Tokens generated by the admin are base64url. Never interpolate a token in a PostgREST filter.
  if (!/^[A-Za-z0-9_-]{16,128}$/.test(token)) return Response.json({ error: 'Unauthorized' }, { status: 401 });
  if (!hasPaymentDatabase()) return unavailablePaymentResponse();
  try {
    const admin = createAdminClient();
    const current = await admin.from('webhook_configs').select('*').eq('provider', 'guru').eq('is_active', true).eq('secret_key', token).limit(2).maybeSingle();
    if (current.error) throw new Error('Configuration unavailable');
    let config = current.data;
    if (!config) {
      const previous = await admin.from('webhook_configs').select('*').eq('provider', 'guru').eq('is_active', true)
        .eq('previous_secret_key', token).gt('previous_secret_expires_at', new Date().toISOString()).limit(2).maybeSingle();
      if (previous.error) throw new Error('Configuration unavailable');
      config = previous.data;
    }
    if (!config || !(secretMatches(token, config.secret_key) || (new Date(config.previous_secret_expires_at ?? 0).getTime() > Date.now() && secretMatches(token, config.previous_secret_key)))) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }
    let payload: Record<string, unknown>;
    try { payload = await readWebhookJson(request); } catch (error) { return invalidWebhookBodyResponse(error); }
    // Test pings verify URL authentication; production events additionally check account binding.
    if (request.headers.get('X-Test-Mode') !== '1' && config.expected_producer_id && guruProducerId(payload) !== config.expected_producer_id) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const preflight = await paymentPreflight(request, config); if (preflight) return preflight;
    let work;
    try { work = normalizeGuru(payload); } catch { return Response.json({ error: 'Invalid purchase or cancellation fields' }, { status: 400 }); }
    if (!work) return Response.json({ received: true, skipped: true });
    const result = await executeWebhookDelivery(work, config);
    return Response.json(result.body, { status: result.status });
  } catch { return unavailablePaymentResponse(); }
}
